23 implement flow
OperationalBina/PipeRT2 pull request #51
Opened 2021-07-25 06:24 UTC by MayoG

Depends on #46

2021-07-26 09:04 UTC, Elon-Abulafia commented on src/pipert2/core/base/flow.py
> +        """Make the flow ready to listen to events and go.
```suggestion
        """Start the flow process.
```

2021-07-26 09:04 UTC, Elon-Abulafia commented on src/pipert2/core/base/flow.py
> +        """The flow process, executing the pipe events that occur
```suggestion
        """The flow process, executing the pipe events that occur.
```

2021-07-26 09:04 UTC, Elon-Abulafia commented on src/pipert2/core/base/flow.py
> +        """Get the events of the flow
```suggestion
        """Get the events of the flow.
```

2021-07-26 10:10 UTC, San-Moshe requested changes

2021-07-27 06:29 UTC, MayoG commented on src/pipert2/core/base/flow.py
> +        while "kill" not in event_names:
kill should stop the entire pipe including the flow's process, stop should only stop the execution of their routines.

2021-07-27 06:30 UTC, MayoG commented on src/pipert2/core/base/flow.py
> +            event_names = self.event_handler.get_names()
We need to know the event names for the execution loop.

2021-07-27 06:32 UTC, MayoG commented on src/pipert2/core/base/flow.py
> +            routine.execute_event(event_name)
The routines execute event method check if the event is used inside them, i think its a solid implementation but it can be changed.

2021-07-27 06:37 UTC, MayoG commented on src/pipert2/core/base/flow.py
> +    def execute_event(self, event_name: str) -> None:
The execute event method is being triggered in the Pipe class so it shouldn't be private

2021-07-27 06:37 UTC, MayoG commented on src/pipert2/core/base/flow.py
> +            for event in event_names:  # Maybe do this in threads to not get stuck on listening to events.
Changed `event` to `event_name`

2021-08-01 09:11 UTC, San-Moshe approved these changes

2021-08-01 09:16 UTC, merged