31 implement network interface
OperationalBina/PipeRT2 pull request #67
Opened 2021-08-30 07:25 UTC by Elon-Abulafia

2021-09-01 07:14 UTC, MayoG requested changes

2021-09-01 07:14 UTC, MayoG commented on src/pipert2/core/managers/network.py
> +        """Rewire the destinations of a given message handler.
given routine*

2021-09-12 08:59 UTC, MayoG submitted a review, later dismissed

2021-09-12 11:19 UTC, San-Moshe approved these changes

2021-09-12 11:19 UTC, merged