29 implement queue network
OperationalBina/PipeRT2 pull request #69
Opened 2021-09-01 11:13 UTC by Elon-Abulafia

depends on #67

2021-09-01 11:36 UTC, tomerdayan168 commented on src/pipert2/core/base/pipe.py
Description about 'self.default_data_transmitter' is missing

2021-09-01 11:38 UTC, tomerdayan168 commented on src/pipert2/core/base/pipe.py
> +            flow_name (str): The name of the flow to be created.
Swap lines between data_transmitter and flow_name by the order of the function's parameters

2021-09-01 12:25 UTC, tomerdayan168 commented on src/pipert2/core/managers/networks/queue_network.py
> +            queue = Queue(maxsize=1)
Config or TODO config

2021-09-01 12:25 UTC, tomerdayan168 commented on src/pipert2/utils/shared_memory/shared_memory_generator.py
> +    return SharedMemory(memory, semaphore, mapfile)
The standard is - try, except,.., else

2021-09-01 12:25 UTC, tomerdayan168 commented on src/pipert2/core/handlers/message_handler.py
> +                if type(self.receive) == callable:
else if

2021-09-01 12:25 UTC, tomerdayan168 commented on src/pipert2/core/handlers/message_handlers/queue_handler.py
> +            raise Exception(f"{self.routine_name}'s output_queue was not initialized when put was called!")
Maybe raise a custom exception instead general exception?

2021-09-12 14:46 UTC, San-Moshe requested changes

2021-09-12 14:46 UTC, San-Moshe commented on src/pipert2/core/handlers/message_handlers/queue_handler.py
> +            raise Exception(f"{self.routine_name}'s output_queue was not initialized when put was called!")
+1

2021-09-12 14:46 UTC, San-Moshe commented on src/pipert2/core/handlers/message_handlers/queue_handler.py
> +                print("The queue is empty")  # TODO: Replace with log
Replace with log :upside_down_face:

2021-09-12 14:46 UTC, San-Moshe commented on tests/pipert/core/base/test_pipe.py
>  def test_link(dummy_pipe: Pipe):
Add another test that check if correct link were established. 
For example: Routine A MessageHandler Destination queue is the right  destination queue

2021-09-12 14:46 UTC, San-Moshe commented on tests/pipert/core/base/test_pipe.py
>  def test_link(dummy_pipe: Pipe):
This is very critical logic in the pipe, we should validate proper behavior precisely.

2021-09-13 12:03 UTC, MayoG requested changes

2021-09-13 12:03 UTC, MayoG commented on src/pipert2/core/managers/networks/queue_network.py
> +
I think it won't work for routine that get their data from multiple routines.

for example:     Routine 'B' will get their data from Routines 'A1' and 'A2'.

2021-09-13 12:03 UTC, MayoG commented on src/pipert2/utils/publish_queue.py
> +            timeout: How long to wait if block is true.
Technically, the timeout will be the given time multiple by the output queues count.

2021-09-14 07:34 UTC, MayoG submitted a review, later dismissed

2021-09-14 08:35 UTC, MayoG approved these changes

2021-09-14 11:19 UTC, San-Moshe approved these changes

2021-09-14 11:19 UTC, merged